export const dummyDataCategory = [
  {
    id: 1,
    name: 'Aneka Bunga',
    name_en: 'Kind of Flowers',
    priority: 1,
    photo: null,
    is_active: 1,
    created_at: '2022-01-06T07:47:08.000Z',
    updated_at: '2022-01-06T07:47:08.000Z',
    deleted_at: null,
    color: '#f54242',
  },
  {
    id: 2,
    name: 'Rangkaian',
    name_en: 'Flower Arrangements ',
    priority: 2,
    photo: null,
    is_active: 1,
    created_at: '2022-01-06T07:47:08.000Z',
    updated_at: '2022-01-06T07:47:08.000Z',
    deleted_at: null,
    color: '#f5a442',
  },
  {
    id: 3,
    name: 'Acara',
    name_en: 'Ceremonial',
    priority: 3,
    photo: null,
    is_active: 1,
    created_at: '2022-01-06T07:47:08.000Z',
    updated_at: '2022-01-06T07:47:08.000Z',
    deleted_at: null,
    color: '#f5428d',
  },
  {
    id: 4,
    name: 'Hadiah Lain',
    name_en: 'Other Gifts',
    priority: 4,
    photo: null,
    is_active: 1,
    created_at: '2022-01-06T07:47:08.000Z',
    updated_at: '2022-01-06T07:47:08.000Z',
    deleted_at: null,
    color: '#368dff',
  },
  {
    id: 5,
    name: 'Bunga Papan',
    name_en: 'Flower Board',
    priority: 5,
    photo: null,
    is_active: 1,
    created_at: '2022-01-06T07:47:08.000Z',
    updated_at: '2022-01-06T07:47:08.000Z',
    deleted_at: null,
    color: '#512fdd',
  },
];
// export const dummyDataProduct = [{}];
import {
  roseDummy,
  sunFlowerDummy,
  edelwisDummy,
  anggrekDummy,
  anggrekHitamDummy,
  bugenvilDummy,
  geraniumDummy,
  pinkDummy,
  sedapDummy,
} from '../assets/dummy';
export const dummyNewProduct = [
  {
    id: 1,
    name: 'Mawar Merah',
    img: roseDummy,
    desc: 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.',
    price: 100000,
  },
  {
    id: 2,
    name: 'Sun Flower',
    img: sunFlowerDummy,
    desc: 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.',
    price: 330000,
  },
  {
    id: 3,
    name: 'Edelwis Flower',
    img: edelwisDummy,
    desc: 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.',
    price: 200000,
  },
  {
    id: 4,
    name: 'Anggrek Bulan',
    img: anggrekDummy,
    desc: 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.',
    price: 250000,
  },
  {
    id: 5,
    name: 'Anggrek Hitam',
    img: anggrekHitamDummy,
    desc: 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.',
    price: 270000,
  },
  {
    id: 6,
    name: 'Bougenvile',
    img: bugenvilDummy,
    desc: 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.',
    price: 250000,
  },
  {
    id: 7,
    name: 'Sedap Malam',
    img: sedapDummy,
    desc: 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.',
    price: 290000,
  },
  {
    id: 8,
    name: 'Mawar Pink',
    img: pinkDummy,
    desc: 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.',
    price: 350000,
  },
  {
    id: 9,
    name: 'Geranium',
    img: geraniumDummy,
    desc: 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.',
    price: 250000,
  },
];

export const dummyCart = [
  {
    id: 1,
    name: 'Mawar Merah',
    img: roseDummy,
    desc: 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.',
    price: 100000,
    type: 'cart',
  },
  {
    id: 2,
    name: 'Sun Flower',
    img: sunFlowerDummy,
    desc: 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.',
    price: 330000,
    type: 'cart',
  },
  // {
  //   id: 3,
  //   name: 'Edelwis Flower',
  //   img: edelwisDummy,
  //   desc: 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.',
  //   price: 200000,
  //   type: 'cart',
  // },
  // {
  //   id: 4,
  //   name: 'Anggrek Bulan',
  //   img: anggrekDummy,
  //   desc: 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.',
  //   price: 250000,
  //   type: 'cart',
  // },
  // {
  //   id: 5,
  //   name: 'Anggrek Hitam',
  //   img: anggrekHitamDummy,
  //   desc: 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.',
  //   price: 270000,
  //   type: 'cart',
  // },
  // {
  //   id: 6,
  //   name: 'Bougenvile',
  //   img: bugenvilDummy,
  //   desc: 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.',
  //   price: 250000,
  //   type: 'cart',
  // },
  // {
  //   id: 7,
  //   name: 'Sedap Malam',
  //   img: sedapDummy,
  //   desc: 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.',
  //   price: 290000,
  //   type: 'cart',
  // },
  // {
  //   id: 8,
  //   name: 'Mawar Pink',
  //   img: pinkDummy,
  //   desc: 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.',
  //   price: 350000,
  //   type: 'cart',
  // },
  // {
  //   id: 9,
  //   name: 'Geranium',
  //   img: geraniumDummy,
  //   desc: 'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.',
  //   price: 250000,
  //   type: 'cart',
  // },
];
